name: Deploy Docs
on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      
      - run: pwd
      - run: pip install mkdocs-material
      - run: echo "PYTHONPATH=/home/runner/work/mkdocs-testing/mkdocs-testing/:/home/runner/work/mkdocs-ci-issue/mkdocs-ci-issue/" >> $GITHUB_ENV
      - run: python -c "import sys; print(sys.path)"
      - run: python -c "import docs.extensions.func_args"
      - run: mkdocs gh-deploy --force --verbose
